// Problem: Find the Difference
// Link: https://leetcode.com/problems/find-the-difference
// Difficulty: Easy
// Approach: Use XOR to find the extra character efficiently

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

public class FindTheDifference {

    public char findDiff(String s, String t){
        char extra = 0;
        for (char c : s.toCharArray()) extra ^= c;
        for (char c : t.toCharArray()) extra ^= c;
        return extra;
    }
    public static void main(String[] args) {
        String s = "";
        String t = "y";

        FindTheDifference c = new FindTheDifference();
        System.out.println(c.findDiff(s, t));
    }
}
